name: Create Release Branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push origin release
      
      - name: Create Pull Request
        env:
          REVIEWERS: "izszzz"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        run: |
          hub pull-request -m "release" -b main -h $BRANCH_NAME -l "PR:draft" -r "$REVIEWERS"