name: Create Release Branch

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout develop
        uses: actions/checkout@v2

      - name: set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Create Release Branch PullRequest
        env:
          GIT_PR_RELEASE_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_PR_RELEASE_BRANCH_STAGING: release
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_LABELS: release
        run: |
          gem install -N git-pr-release -v "1.4.0"
          git-pr-release --no-fetch
