name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          yarn
          yarn build

      - name: Add Workflow
        run: |
          mv ./.github/ ./build/

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" --dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: StaveService/web
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: front_update
