name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: |
          yarn
          yarn build

      - name: Add Workflow
        run: |
          mv ./.github/ ./build/